name: Quick User Update

on:
  push:
    paths:
      - 'user_list.txt'
      - 'blocked_users.txt'

jobs:
  quick-update:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests pytz

      - name: Run quick subscription update (FAST_RUN)
        env:
          FAST_RUN: '1'
        run: |
          python scripts/update_subscriptions.py

      - name: Commit changes if any
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          if git diff --quiet && git diff --staged --quiet; then
            echo "No changes to commit"
          else
            git add -A
            git commit -m "Quick user update [$(date '+%Y-%m-%d %H:%M')]"
            # Pull with rebase strategy to handle concurrent updates
            git pull --rebase origin main
            git push
          fi 
